[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 60

[deploy.env]
PYTHON_VERSION = "3.11.7" 