[build]
builder = "nixpacks"
watchPatterns = ["*.py"]

[deploy]
startCommand = "python -u bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
healthcheckEnabled = true
healthcheckTimeout = 300
healthcheckInterval = 60

[deploy.env]
PYTHON_VERSION = "3.11.7"
NIXPACKS_PYTHON_VERSION = "3.11.7" 